#!/usr/bin/env bash

nix_version=$(nix --version 2> /dev/null)

if [[ $? -eq 0 ]]; then
  printf "Nix is already installed: $nix_version\n" >&2
  return
fi

printf "Installing Nix\n" >&2

curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --determinate $@
